#include "Adherents.h"




void Adherents::emprune_livre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:000000000000107A begin
{
}
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:000000000000107A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adherents::rendre_livre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:000000000000107C begin
{
}
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:000000000000107C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
