#include "Bibliotheque.h"




void Bibliotheque::ajouter_adherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:000000000000107E begin
{
}
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:000000000000107E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliotheque::supprimer_adherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:0000000000001080 begin
{
}
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:0000000000001080 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliotheque::ajouter_document()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:0000000000001082 begin
{
}
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:0000000000001082 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
