#include "emprunte.h"




void emprunte::periode_emprunt()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:00000000000010A3 begin
{
}
// section -87--2-44--18--1f416d3e:16e1cedf03f:-8000:00000000000010A3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
